import json
from pathlib import Path
O=Path('outputs/voronoi_migrate600');frames=[]
for total in range(358,601):
 r=json.load(open(O/'turns'/f'{total:03d}.json'))
 frames.append(dict(step=total-100,total=total,centers=r['after_centers'],cells=r['after_cells'],weights=r['counts_after'],site=r['site'],host=r['departure'].get('host'),kind=r['kind'],status=r['status']))
assert frames[0]['step']==258 and frames[-1]['step']==500
html=r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Voronoi single-step viewer — from 258</title><style>
body{font:15px system-ui;margin:0;background:#f1f5f9;color:#182334}header{background:white;padding:14px 20px;border-bottom:1px solid #cbd5e1;position:sticky;top:0;z-index:10}h1{font-size:21px;margin:0 0 10px}nav{display:flex;gap:10px;align-items:center;flex-wrap:wrap}button,input{font:inherit}button{padding:8px 14px;cursor:pointer}#slider{width:min(36vw,440px)}main{display:flex;gap:12px;padding:12px;justify-content:center}.panel{background:white;width:48%;border-radius:8px;overflow:auto}.panel h2{text-align:center;font-size:17px}svg{display:block;width:100%;min-width:480px;min-height:860px}p{margin:8px 0}small{color:#475569}.key{display:inline-block;background:linear-gradient(90deg,#ffffcc,#fd8d3c,#800026);width:150px;height:12px}#detail{padding:8px 20px;min-height:22px}.zoom{display:flex;gap:8px}input[type=number]{width:66px}button:disabled{opacity:.4;cursor:default}
</style></head><body><header><h1>Single-step viewer · ID (weight)</h1><nav><button id="prev">← Previous</button><button id="next">Next →</button><button id="reset">Back to 258</button><label>Selection <input id="number" type="number" min="258" max="500" value="258"></label><input id="slider" type="range" min="258" max="500" value="258" step="1"><b id="position"></b><label>Map zoom <select id="zoom"><option value="1">100%</option><option value="1.5">150%</option><option value="2">200%</option></select></label></nav><p><span class="key"></span> Weight: 0 → 160+ · Each label is <b>permanent ID (pickup weight)</b>. Cyan: centers involved in the displayed turn.</p><small>Starts paused; no autoplay. Use ← / → keys. Selection numbers follow the graphs: total step = displayed selection + 100. Colors share the previous map’s 0–160 scale; heavier cells saturate. These are saved states, not a running simulation.</small></header><div id="detail"></div><main><section class="panel"><h2 id="leftTitle"></h2><svg id="left" viewBox="0 0 510 1040"></svg></section><section class="panel"><h2 id="rightTitle"></h2><svg id="right" viewBox="0 0 510 1040"></svg></section></main><script>
const frames=__DATA__;let n=0;const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
function el(tag,attrs,parent){const e=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);parent.appendChild(e);return e}
function xy(p){return [20+(p[0]+.2)*48,1008-(p[1]+.3)*48]}
function color(v){const stops=[[255,255,204],[254,217,118],[253,141,60],[227,26,28],[128,0,38]],z=Math.min(160,Math.max(0,v))/160*4,i=Math.min(3,Math.floor(z)),f=z-i;return `rgb(${stops[i].map((x,j)=>Math.round(x+(stops[i+1][j]-x)*f)).join(',')})`}
function center(v){let a=0,x=0,y=0;for(let i=0;i<v.length-1;i++){const p=v[i],q=v[i+1],z=p[0]*q[1]-q[0]*p[1];a+=z;x+=(p[0]+q[0])*z;y+=(p[1]+q[1])*z}return [x/(3*a),y/(3*a)]}
function draw(id,f,active){const svg=$(id);svg.innerHTML='';for(let i=0;i<100;i++){const p=el('polygon',{points:f.cells[i].map(p=>xy(p).join(',')).join(' '),fill:color(f.weights[i]),stroke:active.includes(i)?'#06b6d4':'#64748b','stroke-width':active.includes(i)?2.4:.6},svg);el('title',{},p).textContent=`ID ${i+1}, weight ${f.weights[i]}`}
for(let i=0;i<100;i++){const [x,y]=xy(f.centers[i]);el('circle',{cx:x,cy:y,r:2,fill:'#0369a1'},svg);const [tx,ty]=xy(center(f.cells[i]));el('text',{x:tx,y:ty,'text-anchor':'middle','dominant-baseline':'middle','font-size':8,fill:'#111827',stroke:'white','stroke-width':2.1,'stroke-opacity':.8,'paint-order':'stroke'},svg).textContent=`${i+1} (${f.weights[i]})`}}
function show(){const f=frames[n],p=frames[Math.max(0,n-1)],active=n?[f.site,...(f.host===null?[]:[f.host])]:[];$('leftTitle').textContent=n?`Before · selection ${p.step}`:`Starting state · selection 258`;$('rightTitle').textContent=`Current · selection ${f.step} (total ${f.total})`;draw('left',p,active);draw('right',f,active);$('number').value=f.step;$('slider').value=f.step;$('position').textContent=`${f.step} / 500`;$('prev').disabled=n===0;$('next').disabled=n===frames.length-1;
$('detail').textContent=n===0?'Starting at saved selection 258. Click Next to see 258 → 259.':f.kind==='depart-insert'?`Selection ${f.step}: center ${f.site+1} departs and inserts at host ${f.host+1}. The entire operation is one turn.`:`Selection ${f.step}: center ${f.site+1} · ${f.kind} · ${f.status}.`}
function go(v){n=Math.max(0,Math.min(frames.length-1,Math.round(Number(v))-258));if(!Number.isFinite(n))n=0;show()}
$('prev').onclick=()=>go(257+n);$('next').onclick=()=>go(259+n);$('reset').onclick=()=>go(258);$('slider').oninput=e=>go(e.target.value);$('number').onchange=e=>go(e.target.value);$('zoom').onchange=e=>{for(const id of ['left','right']){$(id).style.width=(Number(e.target.value)*100)+'%'}};
document.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(e.target.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();go(259+n)}if(e.key==='ArrowLeft'){e.preventDefault();go(257+n)}});show();
</script></body></html>'''
path=O/'single_step_from_258.html';path.write_text(html.replace('__DATA__',json.dumps(frames,separators=(',',':'))));print('SAVED',len(frames),'states',path.stat().st_size)
js=path.read_text().split('<script>')[1].split('</script>')[0]
check="const nodes={};function node(){return {style:{},setAttribute(){},appendChild(){}}}global.document={getElementById(id){return nodes[id]||(nodes[id]=node())},createElementNS(){return node()},addEventListener(){}};\n"+js+"\nfor(let k=258;k<=500;k++)go(k);go(258);$('next').onclick();if(n!==1)throw Error('Next');$('prev').onclick();if(n!==0)throw Error('Previous');console.log('243 states and next/previous passed');"
(O/'single_step_check.js').write_text(check)
