import json,pathlib,shutil
root=pathlib.Path('work/Manhattan_Balanced_Hexagons')
D=json.load(open('work/native_input.json'));B=json.load(open('work/compare_data.json'))
history=[json.load(open(p)) for p in sorted(pathlib.Path('work/history').glob('round-*.json'),key=lambda p:int(p.stem.split('-')[1]))]
assert len(history)==163
assert history[-1]['verticesX']==json.load(open('work/guided020_best.json'))['verticesX']
json.dump(history,open(root/'history.json','w'))
data=dict(geometry=D,merged=B['merged'],history=history)
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Manhattan · balanced hexagons</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f5f8fa;color:#203442;font:16px system-ui,sans-serif}main{max-width:1250px;margin:auto;padding:24px}h1{margin:0 0 6px;font-size:30px}p{color:#536875;line-height:1.5}.controls{position:sticky;top:0;background:#f5f8faf2;padding:12px 0;display:flex;gap:12px;align-items:center;flex-wrap:wrap;z-index:2}button{background:#145963;color:white;border:0;border-radius:7px;padding:11px 16px;font:inherit;cursor:pointer}input[type=range]{min-width:180px;flex:1}.cards{display:grid;grid-template-columns:1fr 1fr;gap:20px}.card{background:white;border:1px solid #d9e2e7;border-radius:12px;padding:16px}h2{font-size:20px;margin:0 0 5px}.stats{color:#145963;margin-bottom:10px;font-weight:600}canvas{display:block;width:100%;height:auto}.note{font-size:14px}#status{font-size:18px;font-weight:650;color:#145963}@media(max-width:650px){main{padding:15px}.cards{grid-template-columns:1fr}h1{font-size:25px}}</style>
<main><h1>Exact balance in 38 convex hexagons</h1><p>Same 5,986 Manhattan taxi pickups, 8:00–8:15. The saved run reaches 157 or 158 pickups in every cell. This is a replay of the tested local search; the C++ runner in the download reproduces it.</p>
<div class="controls"><button id="play">Play from start</button><button id="final">Final state</button><input type="range" id="round" min="0" max="162" value="162"><label><input type="checkbox" id="offshore"> Show complete hexagons offshore</label></div><p id="status"></p>
<div class="cards"><section class="card"><h2>K-means + merging</h2><div class="stats">38 regions · variance 1,374</div><canvas id="left" width="640" height="1060"></canvas></section><section class="card"><h2>Local atomic hexagon rule</h2><div class="stats" id="rightstats"></div><canvas id="right" width="640" height="1060"></canvas></section></div>
<p class="note">At the final state: 20 cells contain 158 pickups; 18 contain 157. Independent checks found no cell overlap, full coverage of the modeled island, and every pickup in exactly one cell. All six-sided cells are strictly convex. Lowest shape score 4πA/P²: 0.20215 (bound 0.20). Boundary vertices may move beyond the shoreline.</p>
<p class="note">Each activation proposes independent movements of a vertex and its edge-neighbours. Temperature is determined by the imbalance in the affected cells. Underfilled cells receive proposals toward nearby pickups; geometry and coverage are checked before committing. The prototype simulates agents sequentially and uses a whole-boundary geometry guard; it does not establish distributed convergence.</p>
</main><script>const DATA=__DATA__;
const $=s=>document.getElementById(s),G=DATA.geometry,H=DATA.history,palette=['#8cc7b5','#e9ac93','#b4addd','#efce85','#91b5d9','#c7d99a','#deaac4','#a8ccce'];let timer=null;
const cross=(a,b,p)=>(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]);
function draw(which,groups,full){const cv=$(which),cx=cv.getContext('2d');cx.clearRect(0,0,cv.width,cv.height);let xmin=-.5,xmax=9.8,ymin=-.3,ymax=20.2;if(full){const pp=groups.flatMap(g=>g.polys.flat());xmin=Math.min(xmin,...pp.map(p=>p[0]));xmax=Math.max(xmax,...pp.map(p=>p[0]));ymin=Math.min(ymin,...pp.map(p=>p[1]));ymax=Math.max(ymax,...pp.map(p=>p[1]));}const sc=Math.min((cv.width-30)/(xmax-xmin),(cv.height-30)/(ymax-ymin)),ox=(cv.width-sc*(xmax-xmin))/2,oy=(cv.height-sc*(ymax-ymin))/2,X=x=>ox+(x-xmin)*sc,Y=y=>cv.height-oy-(y-ymin)*sc;
function path(p){cx.beginPath();p.forEach((p,i)=>i?cx.lineTo(X(p[0]),Y(p[1])):cx.moveTo(X(p[0]),Y(p[1])));cx.closePath();}
cx.save();if(!full){path(G.outline);cx.clip();}groups.forEach((g,k)=>{cx.fillStyle=palette[k%palette.length];cx.strokeStyle=full?'#506976':'white';cx.lineWidth=.7;for(const p of g.polys){path(p);cx.globalAlpha=.8;cx.fill();cx.globalAlpha=1;cx.stroke();}});cx.restore();cx.fillStyle='#243946';cx.globalAlpha=.3;for(const p of G.points)cx.fillRect(X(p[0]),Y(p[1]),1.1,1.1);cx.globalAlpha=1;path(G.outline);cx.strokeStyle='#203442';cx.lineWidth=1.4;cx.stroke();cx.font='bold 11px system-ui';cx.textAlign='center';cx.textBaseline='middle';for(const g of groups){if(!g.label)continue;const x=X(g.label[0]),y=Y(g.label[1]),t=String(g.size),w=cx.measureText(t).width;cx.fillStyle='#ffffffcc';cx.fillRect(x-w/2-2,y-6,w+4,12);cx.fillStyle='#203442';cx.fillText(t,x,y);}}
function render(){const k=+$('round').value,s=H[k],verts=s.verticesX.map((x,i)=>[x,s.verticesY[i]]),cells=G.cells.map(r=>r.map(v=>verts[v])),sums=cells.map(()=>[0,0,0]);for(const p of G.points){for(let c=0;c<cells.length;c++){const r=cells[c];if(r.every((a,i)=>cross(a,r[(i+1)%6],p)>=-1e-10)){sums[c][0]+=p[0];sums[c][1]+=p[1];sums[c][2]++;break;}}}const groups=cells.map((r,c)=>({polys:[r],size:s.counts[c],label:sums[c][2]?[sums[c][0]/sums[c][2],sums[c][1]/sums[c][2]]:[$('offshore').checked?r.reduce((a,p)=>a+p[0],0)/6:NaN,r.reduce((a,p)=>a+p[1],0)/6]}));const mean=5986/38,variance=s.counts.reduce((a,n)=>a+(n-mean)**2,0)/38,min=Math.min(...s.counts),max=Math.max(...s.counts);$('rightstats').textContent=`38 hexagons · variance ${variance.toFixed(4)} · ${min}–${max} pickups`;$('status').textContent=k===162?'Round 162: exact integer balance. Every local temperature is zero.':`Round ${k} of 162 · local temperature remains active in imbalanced neighbourhoods`;draw('left',DATA.merged.map(g=>({...g})),false);draw('right',groups,$('offshore').checked);}
$('round').oninput=render;$('offshore').onchange=render;$('final').onclick=()=>{clearInterval(timer);timer=null;$('round').value=162;$('play').textContent='Play from start';render();};$('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('play').textContent='Play';return;}if(+$('round').value===162)$('round').value=0;$('play').textContent='Pause';render();timer=setInterval(()=>{let k=+$('round').value;if(k>=162){clearInterval(timer);timer=null;$('play').textContent='Play from start';return;}$('round').value=k+1;render();},140);};render();</script></html>'''
(root/'Replay.html').write_text(html.replace('__DATA__',json.dumps(data,separators=(',',':'))))
